development:
  access_key_id: AKIAILDZXNELHCFDHFLA
  secret_code: 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

production:
  access_key_id: AKIAILDZXNELHCFDHFLA
  secret_code: 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